name: \\[Bug Report\\] 反馈Bug / 错误
description: 创建一个issue来报告使用的过程中发现的错误等
title: "[Bug] "
labels: ["Bug"]
body:

  - type: checkboxes
    id: checklist
    attributes:
      label: 在开始反馈前，请检查已有的issue：
      description: 如果你的问题是重复的，将不会被回复并直接关闭。
      options:
        - label: 我的问题从未被其他人提及过，且不是重复的。
          required: true
        - label: 我正在使用最新发行版的书源，没有使用过时的。

  - type: textarea
    id: bug
    attributes:
      label: 问题描述
      description: 请对您Bug/错误的现象进行清晰的描述，并尽量简短。（支持Markdown、图片、附件）
    validations:
      required: true

  - type: textarea
    id: step
    attributes:
      label: 复现步骤
      description: 请提供必要的复现行为的步骤。（支持Markdown、图片、附件）
    validations:
      required: true

  - type: textarea
    id: behavior
    attributes:
      label: 预期行为
      description: 请描述此bug的预期行为。（支持Markdown、图片、附件）

  - type: input
    id: legado_ver
    attributes:
      label: 阅读APP版本
      placeholder: "Example: 3.25"
    validations:
      required: true

  - type: dropdown
    id: error_occurred
    attributes:
      label: 软件是否有报错？
      options:
        - "是"
        - "否"

  - type: textarea
    id: log
    attributes:
      label: 日志Log
      description: 请提供含报错的阅读APP日志文件。
      render: shell
    validations:
      required: true
    conditional:
      path: error_occurred
      value: "是"

  - type: textarea
    id: context
    attributes:
      label: 其他信息
      description: 在这里输入任何其他相关信息。（支持Markdown、图片、附件）

  - type: checkboxes
    id: acknowledgements
    attributes:
      label: 注意事项
      description: 请注意：
      options:
        - label: 我已知晓该仓库维护者仅会在能力范围内进行Bug/错误解答修复，能力范围以外的可能不会修复。
          required: true
