name: [Question] 问题提出
description: 我有需要帮助的问题
title: "[Question] "
labels: ["Question"]
body:

  - type: checkboxes
    id: checklist
    attributes:
      label: 检查清单
      description: 如果你的问题是重复的，将不会被回复并直接关闭。
      options:
        - label: 我已经阅读了[Q&A清单](https://github.com/ZWolken/Light-Novel-Yuedu-Source/blob/main/docs/questions.md)，但依然没能得到解答。
          required: true
        - label: 我的问题没有被其他人提及过，且不是重复的。
          required: true

  - type: textarea
    id: bug
    attributes:
      label: 描述
      description: 描述你的问题。
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: 其他信息
      description: 在这里输入任何其他相关信息。
