name: Question
description: 我有需要帮助的问题
title: "[Question] "
labels: ["triage"]
body:

  - type: checkboxes
    id: checklist
    attributes:
      label: 检查清单
      description: 如果你的问题是重复的，将不会被回复直接关闭。
      options:
        - label: 我已经阅读了[docs/questions.md](https://github.com/ZWolken/Light-Novel-Yuedu-Source/blob/main/docs/questions.md)，但没能回答我的问题。
          required: true
        - label: 我的问题没有被其他人提及过，且不是重复的。
          required: true

  - type: textarea
    id: bug
    attributes:
      label: 描述
      description: 描述你的问题。
    validations:
      required: true

  - type: input
    id: legado_ver
    attributes:
      label: 书源版本
      placeholder: "Example: 3.25"
    validations:
      required: true

  - type: textarea
    id: log
    attributes:
      label: 日志Log
      description: 请提供书源的日志文件。
      render: shell

  - type: textarea
    id: context
    attributes:
      label: 其他信息
      description: 在这里输入任何其他相关信息。
