name: Release BookSource JSON

on:
  push:
    tags:
      - '*-*-*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Run booksource_combine script
      run: |
        python src/scripts/booksource_combine/booksource_combine.py

    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        files: src/BookSource/build/*.json
        tag_name: ${{ github.ref }}
        release_name: BookSource_${{ github.ref }}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}